export const TRANSPORT_MODE = Object.freeze({
  WALK: 'WALK',
  BICYCLE: 'BICYCLE',
  DRIVE: 'DRIVE',
  BUS: 'BUS',
  SUBWAY: 'SUBWAY',
  RAIL: 'RAIL',
  TRAM: 'TRAM',
  FERRY: 'FERRY',
  COACH: 'COACH',
  TROLLEYBUS: 'TROLLEYBUS',
  CABLE_CAR: 'CABLE_CAR',
  FUNICULAR: 'FUNICULAR',
  MONORAIL: 'MONORAIL',
  BIKE_SHARE: 'BIKE_SHARE',
  SCOOTER_SHARE: 'SCOOTER_SHARE',
  CAR_SHARE: 'CAR_SHARE',
})

const MOTIS_MODE_MAP = Object.freeze({
  WALK: TRANSPORT_MODE.WALK,
  FOOT: TRANSPORT_MODE.WALK,
  BIKE: TRANSPORT_MODE.BICYCLE,
  BICYCLE: TRANSPORT_MODE.BICYCLE,
  CAR: TRANSPORT_MODE.DRIVE,
  BUS: TRANSPORT_MODE.BUS,
  COACH: TRANSPORT_MODE.COACH,
  SUBWAY: TRANSPORT_MODE.SUBWAY,
  SUBURBAN: TRANSPORT_MODE.SUBWAY,
  METRO: TRANSPORT_MODE.SUBWAY,
  RAIL: TRANSPORT_MODE.RAIL,
  TRAIN: TRANSPORT_MODE.RAIL,
  TRAM: TRANSPORT_MODE.TRAM,
  LIGHT_RAIL: TRANSPORT_MODE.TRAM,
  FERRY: TRANSPORT_MODE.FERRY,
  TROLLEYBUS: TRANSPORT_MODE.TROLLEYBUS,
  AERIAL_LIFT: TRANSPORT_MODE.CABLE_CAR,
  AREAL_LIFT: TRANSPORT_MODE.CABLE_CAR,
  CABLE_CAR: TRANSPORT_MODE.CABLE_CAR,
  GONDOLA: TRANSPORT_MODE.CABLE_CAR,
  FUNICULAR: TRANSPORT_MODE.FUNICULAR,
  MONORAIL: TRANSPORT_MODE.MONORAIL,
  BIKE_SHARING: TRANSPORT_MODE.BIKE_SHARE,
  SCOOTER_SHARING: TRANSPORT_MODE.SCOOTER_SHARE,
  CAR_SHARING: TRANSPORT_MODE.CAR_SHARE,
})

export const TRANSIT_MODES = new Set([
  TRANSPORT_MODE.BUS,
  TRANSPORT_MODE.SUBWAY,
  TRANSPORT_MODE.RAIL,
  TRANSPORT_MODE.TRAM,
  TRANSPORT_MODE.FERRY,
  TRANSPORT_MODE.COACH,
  TRANSPORT_MODE.TROLLEYBUS,
  TRANSPORT_MODE.CABLE_CAR,
  TRANSPORT_MODE.FUNICULAR,
  TRANSPORT_MODE.MONORAIL,
])

export function normalizeTransportMode(value) {
  const key = String(value || '').trim().toUpperCase().replace(/[\s-]+/g, '_')
  return MOTIS_MODE_MAP[key] || key || 'TRANSIT'
}

export function isTransitMode(mode) {
  return TRANSIT_MODES.has(normalizeTransportMode(mode))
}

export function transportModeLabel(mode) {
  switch (normalizeTransportMode(mode)) {
    case TRANSPORT_MODE.WALK: return 'Walk'
    case TRANSPORT_MODE.BICYCLE: return 'Bike'
    case TRANSPORT_MODE.DRIVE: return 'Drive / taxi'
    case TRANSPORT_MODE.BUS: return 'Bus'
    case TRANSPORT_MODE.SUBWAY: return 'MRT / metro'
    case TRANSPORT_MODE.RAIL: return 'Train / rail'
    case TRANSPORT_MODE.TRAM: return 'Tram / light rail'
    case TRANSPORT_MODE.FERRY: return 'Ferry'
    case TRANSPORT_MODE.COACH: return 'Coach'
    case TRANSPORT_MODE.TROLLEYBUS: return 'Trolleybus'
    case TRANSPORT_MODE.CABLE_CAR: return 'Cable car / gondola'
    case TRANSPORT_MODE.FUNICULAR: return 'Funicular'
    case TRANSPORT_MODE.MONORAIL: return 'Monorail'
    case TRANSPORT_MODE.BIKE_SHARE: return 'Bike share'
    case TRANSPORT_MODE.SCOOTER_SHARE: return 'Scooter share'
    case TRANSPORT_MODE.CAR_SHARE: return 'Car share'
    default: return 'Transit'
  }
}
